var EOL = require('os').EOL,
    fs = require('fs'),
    path = require('path'),
    mock = require('mock-fs'),
    MockNode = require('mock-enb/lib/mock-node'),
    FileList = require('enb/lib/file-list'),
    Tech = require('../../techs/priv-client'),
    htmlFilename = path.join(__dirname, '..', 'fixtures', 'index.html'),
    mochaFilename = require.resolve('mocha/mocha.js'),
    chaiFilename = require.resolve('chai/chai.js'),
    runServer = require('../lib/run-server'),
    privJSCore = fs.readFileSync(require.resolve('priv-js/lib/priv.js')),
    block1 = fs.readFileSync('./test/fixtures/block1.priv.js'),
    block2 = fs.readFileSync('./test/fixtures/block2.priv.js');

describe('priv-client', function () {
    afterEach(function () {
        mock.restore();
    });

    it('compiled files should works on client-side', function () {
        var test = [
            'chai.should();',
            'it("autogenerated test", function () {',
            '    blocks.exec(\'block1\').should.equal(1);',
            '    blocks.exec(\'block2\').should.equal(2);',
            '})'
        ].join(EOL);

        return runTest(test);
    });

    it('must use dependencies', function () {
        var test = [
            'chai.should();',
            'it("autogenerated test", function () {',
            '    blocks.exec(\'block1\').should.equal("Hello World");',
            '})'
        ].join(EOL);

        return runTest(test, { dependencies: { depend: 'depend' } }, [
            'module.exports = function (blocks) {',
            '    blocks.declare("block1", function () { return blocks.lib.depend(); });',
            '};'
        ].join(EOL), 'var depend = function () { return "Hello World"; }');
    });

    it('must keep requires in priv files', function () {
        var test = [
            'chai.should();',
            'it("autogenerated test", function () {',
            '    blocks.exec(\'block1\').should.equal("depend");',
            '})'
        ].join(EOL);

        return runTest(test, { keepRequires: true }, [
            'var require = function (arg) { return arg };',
            'var depend = require("depend");',
            'module.exports = function (blocks) {',
            '    blocks.declare("block1", function () { return depend; });',
            '};'
        ].join(EOL));
    });
});

function runTest(testContent, options, template, lib) {
    var bundle,
        fileList,

        scheme = {
            blocks: {
                'block1.priv.js': template || block1,
                'block2.priv.js': block2
            },
            bundle: {},
            // jscs:disable
            node_modules: {
                'priv-js': {
                    lib: {
                        'priv.js': privJSCore
                    }
                },
                fake: {
                    'index.js': 'module.exports = { getText: function () { return "Hello world!"; } };'
                },
                depend: {
                    'index.js': 'module.exports = "CommonJS";'
                }
            },
            // jscs:enable
            'index.html': fs.readFileSync(htmlFilename, 'utf-8'),
            'test.js': testContent,
            'mocha.js': fs.readFileSync(mochaFilename, 'utf-8'),
            'chai.js': fs.readFileSync(chaiFilename, 'utf-8'),
            'some-lib.js': lib || ''
        };

    mock(scheme);

    bundle = new MockNode('bundle');
    fileList = new FileList();
    fileList.loadFromDirSync('blocks');
    bundle.provideTechData('?.files', fileList);

    return bundle.runTech(Tech, options)
        .then(function () {
            return runServer(3000);
        });
}

